# Secretly Production Configuration with Web Dashboard
# This configuration is optimized for production deployment

environment: "production"

locale:
  language: "en"
  fallback_language: "en"

server:
  http:
    enabled: true
    port: "8080"
    protocol_versions: ["1.1", "2.0"]
    swagger_enabled: false  # Disable in production for security
    # Web dashboard settings
    web_assets_path: "/app/web/dist"
    domain: "${SECRETLY_DOMAIN:-localhost}"
    allowed_origins:
      - "https://${SECRETLY_DOMAIN:-localhost}"
      - "https://www.${SECRETLY_DOMAIN:-localhost}"
    tls:
      enabled: false  # TLS handled by reverse proxy
      auto_cert: false
    ratelimit:
      enabled: true
      requests_per_second: 50
      burst: 100
  grpc:
    enabled: true
    port: "9090"
    protocol_versions: ["2.0"]
    reflection_enabled: false  # Disable in production
    tls:
      enabled: false  # TLS handled by reverse proxy
    ratelimit:
      enabled: true
      requests_per_second: 25
      burst: 50

storage:
  type: "local"
  database:
    path: "/app/data/secretly.db"
    max_open_conns: 25
    max_idle_conns: 5
  encryption:
    enabled: true
    use_kek: true
    kek_path: "/app/keys/master.key"
    dek_path: "/app/keys/data.key"

secrets:
  chunking:
    enabled: true
    max_chunk_size_kb: 64
    max_chunks_per_secret: 100
  limits:
    max_secrets_per_user: 10000

telemetry:
  enabled: true
  endpoint: "${TELEMETRY_ENDPOINT:-}"
  log_file: "/app/logs/telemetry.log"
  api_key: "${TELEMETRY_API_KEY:-}"

security:
  enable_file_permission_check: true
  auto_fix_file_permissions: true
  allow_unsafe_file_permissions: false

soft_delete:
  enabled: true
  retention_days: 90  # Longer retention in production

purge:
  enabled: true
  schedule: "0 3 * * 0"  # Weekly on Sunday at 3 AM